services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/frontend
