services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app       
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_service
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - .:/app      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
